export default interface IUser {
  id?: any | null,
  username: string,
  email: string,
  password: string,
  name?: string,
  surname?: string,
  age?: number,
  bornAt?: Date,
  location?: string,
  about?: string,
  image?: string,
  balance?: number,
  phoneNumber?: string,
}